on:
  push:
    branches:
      - master
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

name: Build and publish documentation to GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create virtualenv
      run: python -m venv venv
      
    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install './src[doc]'

    - name: Build docs using Sphinx
      run: |
        source venv/bin/activate
        make pythondoc

    - name: Upload github-pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_build/html

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
